version: '3.7'

# Networks
networks:
  internal:
    name: internal

# Volumes
volumes:
  db_data:
    name: db_data
  rim_data:
    name: rim_data

services:
  db:
    image: postgres
    container_name: db
    hostname: db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    env_file: ./.env

  rim:
    command: tail -F anything
    build:
      args:
        branch: ${BRANCH_DOCKER}
        target: rim-dev
    container_name: rim-dev
    restart: unless-stopped
    volumes:
      - rim_data:/rim
    networks:
      - internal